services:
  mongo:
    image: mongo:8
    container_name: taskforge_mongo_dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: taskforge_mongo-express_dev
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo

  api:
    build: 
      context: .
    container_name: taskforge_api_dev
    ports:
      - "${PORT}:${PORT}"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore: 
            - ./node_module
            - ./dist
        - path: ./package.json
          action: rebuild
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run dev


volumes:
  mongo_data:
